version: '3.8'
services:
  web:
    build:
      context: ./Web
      dockerfile: Dockerfile.web
    ports:
      - '5173:5173'
    volumes:
      - ./Web:/app
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    privileged: true

  arduino:
    build:
      context: ./Arduino
      dockerfile: Dockerfile.arduino
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    privileged: true